[package]
name = "positioner_protobufs"
edition = "2021"
version = "__PACKAGE_VERSION__"
license-file = "LICENSE"
include = ["**/*.rs", "Cargo.toml"]

[dependencies]
prost = "0.13.3"
prost-types = "0.13.3"
